<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-M3S1386" failures="1" tests="3" name="Test" time="10.64" errors="0" timestamp="2023-03-08T15:54:17 IST">
  <testcase classname="projectFolder.TC03_Addbagproduct" name="addbagproduct" time="10.021">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at projectFolder.TC03_Addbagproduct.addbagproduct(TC03_Addbagproduct.java:61)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- addbagproduct -->
  <testcase classname="projectFolder.TC02_verifyLogOutFunctionality" name="verifyLogOutFunctionality" time="10.525"/>
  <testcase classname="projectFolder.TC01_verify_LoginFunctionality" name="verifyloginFunctionality" time="10.592"/>
</testsuite> <!-- Test -->
